#Dev DR vars

env_prod: false
profile: "dev-dr"
aws_region: "eu-west-2" 
#Network defaults
cidr_block: "192.168.0.0/16"
private_availability_zones: ["eu-west-2a", "eu-west-2b"]
public_availability_zones: ["eu-west-2a", "eu-west-2b"]
private_cidr_blocks: ["192.168.1.0/24", "192.168.2.0/24"]
public_cidr_blocks: ["192.168.3.0/24", "192.168.4.0/24"]

#LT + ASG defaults
asg_cplane_key_name: "cplane"
asg_cplane_min_vcpu_count: "2"
asg_cplane_max_vcpu_count: "4"
asg_cplane_min_memory_mib: "2048"
asg_cplane_max_memory_mib: "4096"

